### ISSUE TITLE
Zipimport support

### ISSUE THREAD

**Issue by Berserker66** [Maseya/z3pr-py#3]
Currently the module doesn't work together with https://docs.python.org/3.8/library/zipimport.html , as it tries to load json files directly out of a zip file.

certain distribution methods, like cx_Freeze in my case default to using zipimport.

**Comment by bonimy** [comment]
7f90f8c: Added a `--data-dir` CLI option to specify where you want to load the JSON data files. Does `zipimport` still cry if JSON files simply _exist_ in the module, or is it fine to keep them there?

**Comment by Berserker66** [comment]
zipimport simply ignores them completely. So as long as they're explicitly supplied outside, which I've now done in my integration using the data-dir parameter, it won't complain or crash.
